[build]
  publish = "."
  command = ""

# Use Ubuntu Noble (24.04) instead of Focal (20.04) to avoid deprecation
# Updated: 2024-08-05 to fix deprecation warnings
[build.environment]
  NODE_VERSION = "22"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 